/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/peopleLists/popular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get popular people */
        get: operations["getPopularPeopleFullDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/movie-credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get movie credits of the person by ID */
        get: operations["getMovieCredits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get person images by ID */
        get: operations["getImages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get person details by ID */
        get: operations["getDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movieLists/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get upcoming movies */
        get: operations["getUpcomingMovies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movieLists/top-rated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get top-rated movies */
        get: operations["getTopRatedMovies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movieLists/popular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get popular movies */
        get: operations["getPopularMovies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movieLists/now-playing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get movies currently in theatres */
        get: operations["getNowPlayingMovies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movie/video": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get movie video */
        get: operations["getVideo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movie/movie-credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get movie credits of the person by ID */
        get: operations["getMovieCredits_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movie/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get person images by ID */
        get: operations["getImages_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movie/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get person details by ID */
        get: operations["getDetails_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        KnownFor: {
            /** Format: int32 */
            id?: number;
            adult?: boolean;
            backdrop_path?: string;
            genre_ids?: number[];
            /** Format: double */
            popularity?: number;
            media_type?: string;
            original_language?: string;
            original_title?: string;
            overview?: string;
            poster_path?: string;
            release_date?: string;
            title?: string;
            video?: boolean;
            /** Format: double */
            vote_average?: number;
            /** Format: int32 */
            vote_count?: number;
        };
        PopularPerson: {
            /** Format: int32 */
            id?: number;
            name?: string;
            adult?: boolean;
            /** Format: int32 */
            gender?: number;
            known_for?: components["schemas"]["KnownFor"][];
            known_for_department?: string;
            original_name?: string;
            /** Format: double */
            popularity?: number;
            profile_path?: string;
        };
        MovieCast: {
            /** @enum {string} */
            mediaType?: "movie" | "tv";
            /** Format: int32 */
            id?: number;
            character?: string;
            /** Format: int32 */
            order?: number;
            adult?: boolean;
            backdrop_path?: string;
            genre_ids?: number[];
            original_language?: string;
            original_title?: string;
            overview?: string;
            /** Format: double */
            popularity?: number;
            poster_path?: string;
            release_date?: string;
            title?: string;
            video?: boolean;
            /** Format: double */
            vote_average?: number;
            /** Format: int32 */
            vote_count?: number;
            credit_id?: string;
        };
        MovieCredits: {
            /** Format: int32 */
            id?: number;
            cast?: components["schemas"]["MovieCast"][];
            crew?: components["schemas"]["MovieCrew"][];
        };
        MovieCrew: {
            /** @enum {string} */
            mediaType?: "movie" | "tv";
            /** Format: int32 */
            id?: number;
            department?: string;
            job?: string;
            adult?: boolean;
            backdrop_path?: string;
            genre_ids?: number[];
            original_language?: string;
            original_title?: string;
            overview?: string;
            /** Format: double */
            popularity?: number;
            poster_path?: string;
            release_date?: string;
            title?: string;
            video?: boolean;
            /** Format: double */
            vote_average?: number;
            /** Format: int32 */
            vote_count?: number;
            credit_id?: string;
        };
        Artwork: {
            iso_639_1?: string;
            file_path?: string;
            /** Format: double */
            aspect_ratio?: number;
            /** Format: int32 */
            height?: number;
            /** Format: int32 */
            width?: number;
            /** Format: double */
            vote_average?: number;
            /** Format: int32 */
            vote_count?: number;
        };
        PersonImages: {
            /** Format: int32 */
            id?: number;
            profiles?: components["schemas"]["Artwork"][];
        };
        Cast: {
            /** @enum {string} */
            mediaType?: "movie" | "tv";
        };
        Change: {
            key?: string;
            items?: components["schemas"]["ChangeItem"][];
        };
        ChangeItem: {
            id?: string;
            action?: string;
            time?: string;
            iso_639_1?: string;
            iso_3166_1?: string;
            value?: Record<string, never>;
        };
        ChangeResults: {
            changes?: components["schemas"]["Change"][];
        };
        CombinedPersonCredits: {
            /** Format: int32 */
            id?: number;
            cast?: (components["schemas"]["MovieCast"] | components["schemas"]["TvCast"])[];
            crew?: (components["schemas"]["MovieCrew"] | components["schemas"]["TvCrew"])[];
        };
        Crew: {
            /** @enum {string} */
            mediaType?: "movie" | "tv";
        };
        Data: {
            biography?: string;
        };
        ExternalIds: {
            /** Format: int32 */
            id?: number;
            freebase_mid?: string;
            freebase_id?: string;
            imdb_id?: string;
            /** Format: int32 */
            tvrage_id?: number;
            wikidata_id?: string;
            facebook_id?: string;
            instagram_id?: string;
            tiktok_id?: string;
            twitter_id?: string;
            youtube_id?: string;
        };
        PersonDb: {
            /** Format: int32 */
            id?: number;
            name?: string;
            adult?: boolean;
            also_known_as?: string[];
            biography?: string;
            birthday?: string;
            deathday?: string;
            homepage?: string;
            place_of_birth?: string;
            imdb_id?: string;
            /** Format: double */
            popularity?: number;
            /** @enum {string} */
            gender?: "0" | "1" | "2" | "3";
            known_for_department?: string;
            profile_path?: string;
            combined_credits?: components["schemas"]["CombinedPersonCredits"];
            changes?: components["schemas"]["ChangeResults"];
            external_ids?: components["schemas"]["ExternalIds"];
            images?: components["schemas"]["PersonImages"];
            movie_credits?: components["schemas"]["MovieCredits"];
            tv_credits?: components["schemas"]["TvCredits"];
            translations?: components["schemas"]["Translations"];
        };
        Translation: {
            iso_3166_1?: string;
            iso_639_1?: string;
            name?: string;
            english_name?: string;
            data?: components["schemas"]["Data"];
        };
        Translations: {
            /** Format: int32 */
            id?: number;
            translations?: components["schemas"]["Translation"][];
        };
        TvCast: {
            /** @enum {string} */
            mediaType?: "movie" | "tv";
            /** Format: int32 */
            id?: number;
            name?: string;
            adult?: boolean;
            backdrop_path?: string;
            genre_ids?: number[];
            origin_country?: string[];
            original_language?: string;
            original_name?: string;
            overview?: string;
            /** Format: double */
            popularity?: number;
            poster_path?: string;
            first_air_date?: string;
            /** Format: double */
            vote_average?: number;
            /** Format: int32 */
            vote_count?: number;
            character?: string;
            credit_id?: string;
            /** Format: int32 */
            episode_count?: number;
        };
        TvCredits: {
            /** Format: int32 */
            id?: number;
            cast?: components["schemas"]["TvCast"][];
            crew?: components["schemas"]["TvCrew"][];
        };
        TvCrew: {
            /** @enum {string} */
            mediaType?: "movie" | "tv";
            /** Format: int32 */
            id?: number;
            name?: string;
            adult?: boolean;
            backdrop_path?: string;
            genre_ids?: number[];
            origin_country?: string[];
            original_language?: string;
            original_name?: string;
            overview?: string;
            /** Format: double */
            popularity?: number;
            poster_path?: string;
            first_air_date?: string;
            /** Format: double */
            vote_average?: number;
            /** Format: int32 */
            vote_count?: number;
            credit_id?: string;
            /** Format: int32 */
            episode_count?: number;
            department?: string;
            job?: string;
        };
        Movie: {
            /** Format: int32 */
            id?: number;
            adult?: boolean;
            backdrop_path?: string;
            genre_ids?: number[];
            original_language?: string;
            original_title?: string;
            overview?: string;
            /** Format: double */
            popularity?: number;
            poster_path?: string;
            release_date?: string;
            title?: string;
            video?: boolean;
            /** Format: double */
            vote_average?: number;
            /** Format: int32 */
            vote_count?: number;
        };
        VideoResults: {
            /** Format: int32 */
            id?: number;
            results?: components["schemas"]["video"][];
        };
        video: {
            id?: string;
            name?: string;
            iso_639_1?: string;
            iso_3166_1?: string;
            key?: string;
            site?: string;
            /** Format: int32 */
            size?: number;
            type?: string;
            official?: boolean;
            published_at?: string;
        };
        Credits: {
            /** Format: int32 */
            id?: number;
            cast?: components["schemas"]["Cast"][];
            crew?: components["schemas"]["Crew"][];
        };
        Images: {
            /** Format: int32 */
            id?: number;
            backdrops?: components["schemas"]["Artwork"][];
            logos?: components["schemas"]["Artwork"][];
            posters?: components["schemas"]["Artwork"][];
        };
        AccountStates: {
            /** Format: int32 */
            id?: number;
            favorite?: boolean;
            rated?: Record<string, never>;
            watchlist?: boolean;
        };
        AlternativeTitle: {
            iso_3166_1?: string;
            title?: string;
            type?: string;
        };
        AlternativeTitles: {
            /** Format: int32 */
            id?: number;
            titles?: components["schemas"]["AlternativeTitle"][];
        };
        AuthorDetails: {
            name?: string;
            username?: string;
            avatar_path?: string;
            rating?: string;
        };
        BelongsToCollection: {
            /** Format: int32 */
            id?: number;
            name?: string;
            poster_path?: string;
            backdrop_path?: string;
        };
        KeywordResults: {
            /** Format: int32 */
            id?: number;
            keywords?: components["schemas"]["keyword"][];
        };
        Language: {
            iso_639_1?: string;
            english_name?: string;
            name?: string;
        };
        MovieDb: {
            /** Format: int32 */
            id?: number;
            adult?: boolean;
            backdrop_path?: string;
            belongs_to_collection?: components["schemas"]["BelongsToCollection"];
            /** Format: int32 */
            budget?: number;
            genres?: components["schemas"]["genre"][];
            homepage?: string;
            imdb_id?: string;
            original_language?: string;
            original_title?: string;
            overview?: string;
            /** Format: double */
            popularity?: number;
            poster_path?: string;
            production_companies?: components["schemas"]["production_company"][];
            production_countries?: components["schemas"]["production_country"][];
            release_date?: string;
            /** Format: int64 */
            revenue?: number;
            /** Format: int32 */
            runtime?: number;
            spoken_languages?: components["schemas"]["Language"][];
            status?: string;
            tagline?: string;
            title?: string;
            video?: boolean;
            /** Format: double */
            vote_average?: number;
            /** Format: int32 */
            vote_count?: number;
            account_states?: components["schemas"]["AccountStates"];
            alternative_titles?: components["schemas"]["AlternativeTitles"];
            credits?: components["schemas"]["Credits"];
            changes?: components["schemas"]["ChangeResults"];
            external_ids?: components["schemas"]["ExternalIds"];
            images?: components["schemas"]["Images"];
            keywords?: components["schemas"]["KeywordResults"];
            recommendations?: components["schemas"]["MovieResultsPage"];
            release_dates?: components["schemas"]["ReleaseDateResults"];
            lists?: components["schemas"]["MovieListResultsPage"];
            reviews?: components["schemas"]["ReviewResultsPage"];
            similar?: components["schemas"]["MovieResultsPage"];
            translations?: components["schemas"]["Translations"];
            videos?: components["schemas"]["VideoResults"];
            "watch/providers"?: components["schemas"]["ProviderResults"];
        };
        MovieList: {
            /** Format: int32 */
            id?: number;
            name?: string;
            description?: string;
            /** Format: int32 */
            favorite_count?: number;
            /** Format: int32 */
            item_count?: number;
            iso_639_1?: string;
            list_type?: string;
            poster_path?: string;
        };
        MovieListResultsPage: {
            /** Format: int32 */
            id?: number;
            results?: components["schemas"]["MovieList"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            total_pages?: number;
            /** Format: int32 */
            total_results?: number;
        };
        MovieResultsPage: {
            /** Format: int32 */
            id?: number;
            results?: components["schemas"]["Movie"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            total_pages?: number;
            /** Format: int32 */
            total_results?: number;
        };
        Provider: {
            /** Format: int32 */
            display_priority?: number;
            logo_path?: string;
            /** Format: int32 */
            provider_id?: number;
            provider_name?: string;
        };
        ProviderResults: {
            /** Format: int32 */
            id?: number;
            results?: {
                [key: string]: components["schemas"]["WatchProviders"];
            };
        };
        ReleaseDate: {
            certification?: string;
            descriptors?: Record<string, never>[];
            iso_639_1?: string;
            release_date?: string;
            note?: string;
            /** @enum {string} */
            type?: "1" | "2" | "3" | "4" | "5" | "6";
        };
        ReleaseDateResults: {
            /** Format: int32 */
            id?: number;
            results?: components["schemas"]["ReleaseInfo"][];
        };
        ReleaseInfo: {
            iso_3166_1?: string;
            release_dates?: components["schemas"]["ReleaseDate"][];
        };
        Review: {
            id?: string;
            author?: string;
            author_details?: components["schemas"]["AuthorDetails"];
            content?: string;
            created_at?: string;
            updated_at?: string;
            url?: string;
        };
        ReviewResultsPage: {
            /** Format: int32 */
            id?: number;
            results?: components["schemas"]["Review"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            total_pages?: number;
            /** Format: int32 */
            total_results?: number;
        };
        WatchProviders: {
            link?: string;
            rent?: components["schemas"]["Provider"][];
            buy?: components["schemas"]["Provider"][];
            flatrate?: components["schemas"]["Provider"][];
        };
        genre: {
            /** Format: int32 */
            id?: number;
            name?: string;
        };
        keyword: {
            /** Format: int32 */
            id?: number;
            name?: string;
        };
        production_company: {
            /** Format: int32 */
            id?: number;
            name?: string;
            logo_path?: string;
            origin_country?: string;
        };
        production_country: {
            iso_3166_1?: string;
            name?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPopularPeopleFullDetails: {
        parameters: {
            query?: {
                /** @description Language (e.g. ru-RU) */
                language?: string;
                /** @description Page number */
                page?: number;
                /** @description Limit number of people to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PopularPerson"][];
                };
            };
        };
    };
    getMovieCredits: {
        parameters: {
            query: {
                /**
                 * @description ID of the person
                 * @example 976
                 */
                id: number;
                /**
                 * @description Language code (ISO 639-1)
                 * @example ru
                 */
                language?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MovieCredits"];
                };
            };
        };
    };
    getImages: {
        parameters: {
            query: {
                /**
                 * @description ID of the person
                 * @example 976
                 */
                id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PersonImages"];
                };
            };
        };
    };
    getDetails: {
        parameters: {
            query?: {
                /**
                 * @description ID of the person
                 * @example 976
                 */
                id?: number;
                /**
                 * @description Language code (ISO 639-1)
                 * @example ru
                 */
                language?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PersonDb"];
                };
            };
        };
    };
    getUpcomingMovies: {
        parameters: {
            query?: {
                language?: string;
                page?: number;
                region?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Movie"][];
                };
            };
        };
    };
    getTopRatedMovies: {
        parameters: {
            query?: {
                language?: string;
                page?: number;
                region?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Movie"][];
                };
            };
        };
    };
    getPopularMovies: {
        parameters: {
            query?: {
                /** @description Language (e.g. ru-RU) */
                language?: string;
                /** @description Page number */
                page?: number;
                /** @description Region (e.g. RU) */
                region?: string;
                /** @description Limit (e.g. 10) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Movie"][];
                };
            };
        };
    };
    getNowPlayingMovies: {
        parameters: {
            query?: {
                language?: string;
                page?: number;
                region?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Movie"][];
                };
            };
        };
    };
    getVideo: {
        parameters: {
            query: {
                /** @description id movie */
                id: number;
                /** @description language */
                language?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VideoResults"];
                };
            };
        };
    };
    getMovieCredits_1: {
        parameters: {
            query: {
                /**
                 * @description ID of the movie
                 * @example 976
                 */
                id: number;
                /**
                 * @description Language code (ISO 639-1)
                 * @example ru
                 */
                language?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Credits"];
                };
            };
        };
    };
    getImages_1: {
        parameters: {
            query: {
                /**
                 * @description ID of the movie
                 * @example 976
                 */
                id: number;
                /** @description language */
                language?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Images"];
                };
            };
        };
    };
    getDetails_1: {
        parameters: {
            query: {
                /**
                 * @description ID of the movie
                 * @example 976
                 */
                id: number;
                /**
                 * @description Language code (ISO 639-1)
                 * @example ru
                 */
                language?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MovieDb"];
                };
            };
        };
    };
}
